[tool.poetry]
name = "podcasts"
version = "0.1.0"
description = ""
authors = ["Peter Rice <peter@peterrice.xyz>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.27.1"
feedparser = "^6.0.10"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]
mypy = "^0.960"
pylint = "^2.13.9"
black = "^22.3.0"
types-requests = "^2.27.27"

[tool.poetry.scripts]
podcasts = "podcasts.main:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
