[tool.poetry]
name = "podcasts"
version = "0.1.0"
description = ""
authors = ["Peter Rice <peter@peterrice.xyz>"]
license = "AGPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.27.1"
feedparser = "^6.0.10"
PyYAML = "^6.0"
SQLAlchemy = {extras = ["sqlite"], version = "^1.4.36"}
Flask = "^2.1.2"
dacite = "^1.6.0"
Flask-HTTPAuth = "^4.7.0"
Flask-SQLAlchemy = "^2.5.1"

[tool.poetry.group.dev.dependencies]
mypy = "^0.960"
black = "^22.3.0"
types-requests = "^2.27.27"
types-PyYAML = "^6.0.7"
SQLAlchemy = {extras = ["mypy"], version = "^1.4.36"}
alembic = "^1.9.1"
ruff = "*"
python-lsp-server = "*"
pylsp-mypy = "*"
python-lsp-black = "*"
python-lsp-ruff = "*"

[tool.poetry.scripts]
fetch-podcasts = "podcasts.fetch:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
select = [
  "E",
  "F",
  "W",
  "I",
  "UP",
  "N",
  "ANN",
  "S",
  "B",
  "C4",
  "SIM",
  "ARG",
]
target-version = "py39"
ignore = [
  "E501", # line too long
  "ANN101", # annotate self
  "ANN102", # annotate cls
]

[tool.pylsp-mypy]
strict = true
