[tool.poetry]
name = "podcasts"
version = "0.1.0"
description = ""
authors = ["Peter Rice <peter@peterrice.xyz>"]
license = "AGPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.27.1"
feedparser = "^6.0.10"
PyYAML = "^6.0"
SQLAlchemy = {extras = ["sqlite"], version = "^1.4.36"}
Flask = "^2.1.2"
dacite = "^1.6.0"
Flask-HTTPAuth = "^4.7.0"
Flask-SQLAlchemy = "^2.5.1"

[tool.poetry.group.dev.dependencies]
mypy = "^0.960"
pylint = "^2.13.9"
black = "^22.3.0"
types-requests = "^2.27.27"
types-PyYAML = "^6.0.7"
SQLAlchemy = {extras = ["mypy"], version = "^1.4.36"}
isort = "^5.10.1"
alembic = "^1.9.1"

[tool.poetry.scripts]
fetch-podcasts = "podcasts.fetch:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.pylint.typecheck]
ignored-classes = ["SQLAlchemy", "scoped_session"]

[tool.pylint."messages control"]
disable = [
  "raw-checker-failed",
  "bad-inline-option",
  "locally-disabled",
  "file-ignored",
  "suppressed-message",
  "useless-suppression",
  "deprecated-pragma",
  "use-symbolic-message-instead",
  "missing-module-docstring",
  "missing-class-docstring",
  "missing-function-docstring",
  "invalid-name",
  "too-few-public-methods"
]
